In [38]:
# Solution A
import numpy as np
import math

A = np.array([[1, 0, 4],[5, 2, -2],[2, 9, 3]])
print(A)
print('\n')

# Let there be B matrix where the conditions for the Jacobi iterative algorithm are satisfied
B = np.array([[5, 1, 2],[1, 4, 1],[2, 2, 5]])
print(B)
print('\n')

# Now let us find a P projection that satisfies that P*A = B
A_inv = np.linalg.inv(A)
P = B @ A_inv
print(P)

[[ 1  0  4]
 [ 5  2 -2]
 [ 2  9  3]]


[[5 1 2]
 [1 4 1]
 [2 2 5]]


[[ 0.97340426  0.83510638 -0.07446809]
 [-0.05851064  0.03723404  0.43617021]
 [ 1.14361702  0.09042553  0.20212766]]


In [74]:
# Solution B
A = np.array([[1, 0, 4],[5, 2, -2],[2, 9, 3]]) # Example Matrix
B = A.copy()
A_diag = np.diag(A)
np.fill_diagonal(B,0)
result = A_diag - B.sum(axis=1)
print(result)

[-3 -1 -8]


In [54]:
# Solution C
import sys

A = np.random.rand(11,10)
b = np.random.rand(11)

x_h = np.linalg.lstsq(A,b,rcond=None)[0]

print(x_h)
print('\n')

# Error of the approximation
err = A@x_h-b
print(err)

[-0.05468778  1.32919191  0.0531176   1.18088349  0.64996597 -0.78496649
 -0.23203506 -0.44700253 -0.00891053 -0.12033058]


[-0.02102964  0.00784056  0.01314322  0.03109848 -0.05399105 -0.02577736
  0.03080391  0.05045037 -0.0387521  -0.02873585  0.0255315 ]
