In [65]:
import numpy as np 
import math

# Question A
u = np.arange(10)
v = np.arange(10,20,1)
print(u)
print(v)
print('\n')
resultA = np.dstack((u, v)).flatten()
print(resultA)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


[ 0 10  1 11  2 12  3 13  4 14  5 15  6 16  7 17  8 18  9 19]


In [79]:
# Question B
v = np.random.rand(20)
mask = np.where((0.4 < v) & (v < 0.6))
resultB = np.delete(v, mask)
print(v)
print(mask)
print('\n')
print(resultB)

[0.96419494 0.94214573 0.90892838 0.00758025 0.23694951 0.20092585
 0.19327954 0.25893381 0.0766319  0.62777083 0.4766405  0.66459233
 0.99140189 0.93673875 0.85736049 0.18249053 0.32459577 0.77650475
 0.37238939 0.60951804]
(array([10], dtype=int64),)


[0.96419494 0.94214573 0.90892838 0.00758025 0.23694951 0.20092585
 0.19327954 0.25893381 0.0766319  0.62777083 0.66459233 0.99140189
 0.93673875 0.85736049 0.18249053 0.32459577 0.77650475 0.37238939
 0.60951804]


In [81]:
# Question C
v = np.random.rand(100)
print(v)

v_new[0] = v[0]
for j in range(1, len(v)):
    v_new[j] = v[j] - v[j-1]

print('\n')
print(v_new)

[0.05667976 0.20841072 0.93439901 0.19086831 0.69819673 0.01175064
 0.76753936 0.12642581 0.77389685 0.71428313 0.81942775 0.78350537
 0.02232857 0.59614511 0.72087834 0.86214311 0.41942291 0.31449444
 0.41908653 0.03752238 0.19408088 0.86458635 0.99315404 0.80818951
 0.03836532 0.81695101 0.34846786 0.05186736 0.1363173  0.62609831
 0.67332839 0.33797942 0.52833696 0.4068219  0.8729878  0.31938988
 0.20011216 0.73422057 0.46783841 0.47259827 0.18994534 0.54312914
 0.42071515 0.47559002 0.58408335 0.81103742 0.38079075 0.3006631
 0.91998749 0.96777448 0.78635849 0.53384599 0.46677861 0.90891085
 0.38050168 0.73540031 0.98563088 0.3642446  0.53590519 0.75481239
 0.05668014 0.60253703 0.63042903 0.50537218 0.20776779 0.64069836
 0.19889893 0.04471711 0.05035187 0.95727934 0.15640324 0.44068862
 0.7622201  0.57803303 0.4993077  0.13286146 0.73539756 0.44510938
 0.26250906 0.21055205 0.72901675 0.95029434 0.13708902 0.62408818
 0.05753584 0.28560449 0.74402691 0.93176476 0.63468924 0.97005